(function(){
  const root=document.querySelector('[data-mjr-scholarships]');
  if(!root||root.dataset.ready)return;
  root.dataset.ready='1';
  const feedUrl=root.dataset.feed||'scholarships.json';
  const heading=root.dataset.embedded==='true'?'h2':'h1';
  const state={group:'all',q:'',category:'all',level:'all',region:'all',scope:'all',sort:'deadline',records:[]};
  const media=['Journalism & News','Radio & Podcasting','Television & Video','Digital Media','Public Relations & Communications','Music Industry','Production & Multimedia','Broadcast Engineering & Technology','Advertising & Media Sales'];
  const general=['Any Major','Academic Achievement','Financial Need','Community Service','First-Generation Students','Veterans & Military Families','Diversity & Identity','Geographic & State Residency','Employer, Union & Family Affiliations'];
  root.innerHTML=`<section class="mjr-scholarships" aria-label="Scholarship search"><header class="mjr-hero"><div class="mjr-hero-brand"><img src="https://www.mediajobsreport.com/images/Social-Profile-Pic-2-Media-Jobs-Report-Social-Media-Icon.png" alt="Media Jobs Report"></div><div class="mjr-hero-copy"><p class="mjr-eyebrow">Media Jobs Report Student Resource</p><${heading}>MJR Scholarship Search</${heading}><p class="mjr-hero-intro">Find funding and career-development opportunities for media, communications, music-industry and general degree paths.</p></div><div class="mjr-hero-status"><span aria-label="Source information"><span aria-hidden="true">&#10003;</span> Official provider links reviewed regularly.</span></div></header><div class="mjr-tabs" role="tablist" aria-label="Opportunity type"><button type="button" class="mjr-tab active" data-group="all" role="tab" aria-selected="true">All Opportunities</button><button type="button" class="mjr-tab" data-group="media" role="tab" aria-selected="false">Media & Communications</button><button type="button" class="mjr-tab" data-group="general" role="tab" aria-selected="false">General Scholarships</button></div><div class="mjr-tools"><label class="mjr-sr" for="mjr-search">Search scholarships</label><input id="mjr-search" class="mjr-search" type="search" placeholder="Search by scholarship, provider, school or keyword" autocomplete="off"><div class="mjr-filters"><label><span>Category</span><select data-filter="category"></select></label><label><span>Education level</span><select data-filter="level"></select></label><label><span>State or region</span><select data-filter="region"></select></label><label><span>Availability</span><select data-filter="scope"><option value="all">All availability</option><option value="open">Open to any school</option><option value="school">Institution-specific</option></select></label><label><span>Sort</span><select data-filter="sort"><option value="deadline">Deadline: soonest</option><option value="title">Name: A–Z</option><option value="provider">Provider: A–Z</option></select></label></div></div><div class="mjr-summary"><span data-count role="status" aria-live="polite">Loading scholarship opportunities…</span><button type="button" class="mjr-clear">Clear filters</button></div><div class="mjr-grid" data-results aria-busy="true"><div class="mjr-loading">Loading scholarship opportunities…</div></div><footer class="mjr-note"><strong>Please verify before applying.</strong> Scholarship details may change. Review eligibility, deadlines and application requirements on the official provider website. Media Jobs Report is not affiliated with or endorsed by the listed providers.</footer></section>`;
  const el={tabs:[...root.querySelectorAll('.mjr-tab')],search:root.querySelector('.mjr-search'),category:root.querySelector('[data-filter="category"]'),level:root.querySelector('[data-filter="level"]'),region:root.querySelector('[data-filter="region"]'),scope:root.querySelector('[data-filter="scope"]'),sort:root.querySelector('[data-filter="sort"]'),count:root.querySelector('[data-count]'),results:root.querySelector('[data-results]')};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${v}T00:00:00Z`)):'Deadline to be announced';
  const now=()=>new Date().toISOString().slice(0,10);
  function status(x){if(x.opens&&x.opens>now())return['Opens soon','soon'];if(!x.deadline)return['Deadline TBA','tba'];const d=Math.ceil((Date.parse(x.deadline)-Date.parse(now()))/86400000);if(d<0)return['Next cycle TBA','tba'];if(d<=30)return['Deadline approaching','approaching'];return['Open now','open']}
  const options=(label,values)=>`<option value="all">${label}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');
  function populate(){const cats=state.group==='media'?media:state.group==='general'?general:[...media,...general];el.category.innerHTML=options('All categories',cats);el.level.innerHTML=options('All education levels',[...new Set(state.records.flatMap(x=>x.educationLevels||[]))].sort());el.region.innerHTML=options('All states & regions',[...new Set(state.records.flatMap(x=>x.states||[]))].sort((a,b)=>a==='Nationwide'?-1:b==='Nationwide'?1:a.localeCompare(b)))}
  function render(){const q=state.q.toLowerCase();const rows=state.records.filter(x=>(state.group==='all'||x.programGroup===state.group)&&(state.category==='all'||x.categories.includes(state.category))&&(state.level==='all'||(x.educationLevels||[]).includes(state.level))&&(state.region==='all'||(x.states||[]).includes(state.region))&&(state.scope==='all'||(state.scope==='school'?x.institutionSpecific:!x.institutionSpecific))&&(!q||[x.title,x.provider,x.summary,x.eligibility,x.institution,...x.categories,...(x.states||[])].filter(Boolean).join(' ').toLowerCase().includes(q)));rows.sort((a,b)=>state.sort==='title'?a.title.localeCompare(b.title):state.sort==='provider'?a.provider.localeCompare(b.provider):(a.deadline||'9999-12-31').localeCompare(b.deadline||'9999-12-31'));el.count.textContent=`Showing ${rows.length} of ${state.records.length} opportunities`;el.results.setAttribute('aria-busy','false');el.results.innerHTML=rows.length?rows.map(x=>{const s=status(x);return `<article class="mjr-card ${x.featured?'featured':''}"><div class="mjr-badges">${x.featured?'<span class="mjr-badge">Featured</span>':''}<span class="mjr-badge">${x.programGroup==='media'?'Media & Communications':'General'}</span>${x.institutionSpecific?'<span class="mjr-badge school">Institution-specific</span>':''}<span class="mjr-badge status-${s[1]}">${s[0]}</span></div><h3>${esc(x.title)}</h3><p class="mjr-provider">${esc(x.provider)}</p><div class="mjr-meta"><div><span>Award</span><strong>${esc(x.award||'Varies')}</strong></div><div><span>Deadline</span><strong>${esc(fmt(x.deadline))}</strong></div></div><p>${esc(x.summary||'')}</p><p><strong>Who can apply:</strong> ${esc(x.eligibility||'See official details.')}</p>${x.verifiedOn?`<p class="mjr-verified">Source reviewed ${esc(fmt(x.verifiedOn))}</p>`:''}<a class="mjr-link" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">View Official Details <span aria-hidden="true">↗</span><span class="mjr-sr"> (opens in a new tab)</span></a></article>`}).join(''):'<div class="mjr-empty"><strong>No matching opportunities found.</strong><br>Try clearing one or more filters.</div>'}
  function load(){el.results.setAttribute('aria-busy','true');fetch(feedUrl,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(feed=>{if(!Array.isArray(feed.records))throw Error();state.records=feed.records;populate();render()}).catch(()=>{el.count.textContent='Unable to load opportunities';el.results.setAttribute('aria-busy','false');el.results.innerHTML='<div class="mjr-empty"><strong>The scholarship directory could not be loaded.</strong><br>Please check your connection and try again.<br><button type="button" class="mjr-retry">Try again</button></div>';el.results.querySelector('.mjr-retry').onclick=load})}
  el.tabs.forEach(b=>b.onclick=()=>{state.group=b.dataset.group;state.category='all';el.tabs.forEach(t=>{const on=t===b;t.classList.toggle('active',on);t.setAttribute('aria-selected',on)});populate();render()});
  el.search.oninput=()=>{state.q=el.search.value.trim();render()};['category','level','region','scope','sort'].forEach(k=>el[k].onchange=()=>{state[k]=el[k].value;render()});root.querySelector('.mjr-clear').onclick=()=>{Object.assign(state,{q:'',category:'all',level:'all',region:'all',scope:'all',sort:'deadline'});el.search.value='';el.category.value=el.level.value=el.region.value=el.scope.value='all';el.sort.value='deadline';render()};load();
})();
