(function(){
  const root=document.querySelector('[data-mjr-scholarships]');
  if(!root)return;
  const feedUrl=root.dataset.feed||'scholarships.json';
  const state={group:'all',q:'',category:'all',level:'all',scope:'all',sort:'deadline',records:[]};
  const mediaCategories=['Journalism & News','Radio & Podcasting','Television & Video','Digital Media','Public Relations & Communications','Music Industry','Production & Multimedia','Broadcast Engineering & Technology','Advertising & Media Sales'];
  const generalCategories=['Any Major','Academic Achievement','Financial Need','Community Service','First-Generation Students','Veterans & Military Families','Diversity & Identity','Geographic & State Residency','Employer, Union & Family Affiliations'];
  root.innerHTML=`<section class="mjr-scholarships"><header class="mjr-hero"><p class="mjr-eyebrow">Student & Career Resource</p><h1>MJR Scholarships & Fellowships</h1><p>Find funding and career-development opportunities for media, communications, music-industry and general degree paths.</p></header><div class="mjr-tabs" role="tablist"><button class="mjr-tab active" data-group="all">All Opportunities</button><button class="mjr-tab" data-group="media">Media & Communications</button><button class="mjr-tab" data-group="general">General Scholarships</button></div><div class="mjr-tools"><input class="mjr-search" type="search" placeholder="Search by scholarship, provider, school or keyword" aria-label="Search scholarships"><div class="mjr-filters"><select data-filter="category" aria-label="Category"><option value="all">All categories</option></select><select data-filter="level" aria-label="Education level"><option value="all">All education levels</option></select><select data-filter="scope" aria-label="Availability"><option value="all">All availability</option><option value="open">Open to any school</option><option value="school">Institution-specific</option></select><select data-filter="sort" aria-label="Sort"><option value="deadline">Deadline: soonest</option><option value="title">Name: A–Z</option><option value="provider">Provider: A–Z</option></select></div></div><div class="mjr-summary"><span data-count>Loading opportunities…</span><button class="mjr-clear">Clear filters</button></div><div class="mjr-grid" data-results></div></section>`;
  const el={tabs:[...root.querySelectorAll('.mjr-tab')],search:root.querySelector('.mjr-search'),category:root.querySelector('[data-filter="category"]'),level:root.querySelector('[data-filter="level"]'),scope:root.querySelector('[data-filter="scope"]'),sort:root.querySelector('[data-filter="sort"]'),count:root.querySelector('[data-count]'),results:root.querySelector('[data-results]')};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=v=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${v}T00:00:00Z`)):'Deadline to be announced';
  function populate(){
    const categories=state.group==='media'?mediaCategories:state.group==='general'?generalCategories:[...mediaCategories,...generalCategories];
    el.category.innerHTML='<option value="all">All categories</option>'+categories.map(x=>`<option>${esc(x)}</option>`).join('');
    const levels=[...new Set(state.records.flatMap(x=>x.educationLevels||[]))].sort();
    el.level.innerHTML='<option value="all">All education levels</option>'+levels.map(x=>`<option>${esc(x)}</option>`).join('');
  }
  function render(){
    const q=state.q.toLowerCase();
    let rows=state.records.filter(x=>(state.group==='all'||x.programGroup===state.group)&&(state.category==='all'||x.categories.includes(state.category))&&(state.level==='all'||(x.educationLevels||[]).includes(state.level))&&(state.scope==='all'||(state.scope==='school'?x.institutionSpecific:!x.institutionSpecific))&&(!q||[x.title,x.provider,x.summary,x.eligibility,x.institution,...x.categories].filter(Boolean).join(' ').toLowerCase().includes(q)));
    rows.sort((a,b)=>state.sort==='title'?a.title.localeCompare(b.title):state.sort==='provider'?a.provider.localeCompare(b.provider):(a.deadline||'9999-12-31').localeCompare(b.deadline||'9999-12-31'));
    el.count.textContent=`Showing ${rows.length} of ${state.records.length} opportunities`;
    el.results.innerHTML=rows.length?rows.map(x=>`<article class="mjr-card ${x.featured?'featured':''}"><div class="mjr-badges">${x.featured?'<span class="mjr-badge">Featured</span>':''}<span class="mjr-badge">${x.programGroup==='media'?'Media & Communications':'General'}</span>${x.institutionSpecific?'<span class="mjr-badge school">Institution-specific</span>':''}</div><h2>${esc(x.title)}</h2><p class="mjr-provider">${esc(x.provider)}</p><div class="mjr-meta"><div><span>Award</span><strong>${esc(x.award||'Varies')}</strong></div><div><span>Deadline</span><strong class="mjr-status-open">${esc(date(x.deadline))}</strong></div></div><p>${esc(x.summary||'')}</p><p><strong>Who can apply:</strong> ${esc(x.eligibility||'See official details.')}</p><a class="mjr-link" href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">View Official Details</a></article>`).join(''):'<div class="mjr-empty"><strong>No matching opportunities found.</strong><br>Try clearing one or more filters.</div>';
  }
  el.tabs.forEach(btn=>btn.addEventListener('click',()=>{state.group=btn.dataset.group;state.category='all';el.tabs.forEach(x=>x.classList.toggle('active',x===btn));populate();render()}));
  el.search.addEventListener('input',()=>{state.q=el.search.value.trim();render()});
  ['category','level','scope','sort'].forEach(key=>el[key].addEventListener('change',()=>{state[key]=el[key].value;render()}));
  root.querySelector('.mjr-clear').addEventListener('click',()=>{state.q='';state.category='all';state.level='all';state.scope='all';state.sort='deadline';el.search.value='';el.category.value=el.level.value=el.scope.value='all';el.sort.value='deadline';render()});
  fetch(feedUrl,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(feed=>{state.records=feed.records||[];populate();render()}).catch(()=>{el.count.textContent='Unable to load opportunities';el.results.innerHTML='<div class="mjr-empty"><strong>The scholarship directory could not be loaded.</strong><br>Please try again shortly.</div>'});
})();
